spring:
  web:
    resources:
      add-mappings: false
  application:
    name:
      api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:80
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=X-powered-By,Bin Solutions
            - RewritePath=/auth/(?<remaining>.*), /api/v1/${remaining}

server:
  port: 8082
